# (on-screen line + voiceover, Tenor search used to find the clip)
LINES = [
 ("So apparently food doesn't count if you eat it standing up", "eating standing up"),
 ("Or off someone else's plate", "stealing food from plate"),
 ("Not you cleaning up your kid's nuggets like it's a chore", "chicken nuggets"),
 ("You weren't hungry", "suspicious look"),
 ("You just couldn't let four fries go to waste", "eating fries"),
 ("The way you taste the pasta while you're cooking", "tasting food cooking"),
 ("like five separate times", "again"),
 ("just to check the salt", "salt bae"),
 ("The salt was fine the first time babe", "gordon ramsay"),
 ("And the broken cookies", "broken cookie"),
 ("Those are basically crumbs so they don't count either", "crumbs"),
 ("Funny how you never count the creamer", "pouring coffee creamer"),
 ("Or the chips you grabbed walking past the pantry", "grabbing chips"),
 ("Or the one bite of his dessert", "one bite"),
 ("that was somehow half of it", "eating cake"),
 ("I love how a drink with whipped cream on top is still just a coffee to you", "whipped cream"),
 ("Then you get to dinner and swear you barely ate today", "innocent face"),
 ("Girl", "tyra banks"),
 ("I watched you eat all day", "i saw that"),
 ("It just came in bites", "tiny bite"),
 ("And apparently bites don't have calories", "math lady"),
 ("Be so serious", "be serious"),
 ("Your body was there for every single one", "i see you"),
 ("It counted all of them", "count von count"),
 ("Even the ones you ate over the sink", "raccoon eating"),
]
END = "send this to the friend who swears she barely ate today"
