# (on-screen line + voiceover, Tenor search used to find the clip) - animated / illustrated clips only
LINES = [
 ("Sometimes moving on from someone toxic", "spongebob walking away"),
 ("doesn't feel good at first.", "spongebob sad"),
 ("And I think that's the part nobody really prepares you for.", "cartoon shocked"),
 ("You can know someone isn't good for you", "red flag cartoon"),
 ("and still miss them.", "cartoon miss you"),
 ("You can know you made the right decision", "cartoon nodding"),
 ("and still wanna text them.", "anime phone"),
 ("Because you're not just letting go of the bad parts.", "letting go balloon"),
 ("You're letting go of the good mornings.", "good morning cartoon"),
 ("The inside jokes.", "cartoon laughing"),
 ("The version of them you kept hoping would eventually become the whole person.", "anime rain"),
 ("And some days you're gonna remember one good moment", "cartoon daydreaming"),
 ("and suddenly forget the 47 reasons you left.", "cartoon confused"),
 ("Your brain is annoying like that.", "spongebob brain"),
 ("But missing someone isn't always a sign", "winnie the pooh thinking"),
 ("that you're supposed to go back.", "cartoon shaking head no"),
 ("Sometimes it just means they mattered to you.", "anime tears"),
 ("And you can let someone matter", "cartoon hug"),
 ("without letting them keep hurting you.", "cartoon closing door"),
 ("Eventually you stop checking.", "cartoon throwing phone"),
 ("You stop wondering what they're doing.", "cartoon shrug"),
 ("You go a whole day without thinking about them.", "anime happy"),
 ("Then one day you realize...", "cartoon realization"),
 ("you don't actually want them back.", "cartoon no thanks"),
 ("You just needed enough time", "spongebob waiting"),
 ("to remember what peace felt like without them.", "ghibli peaceful"),
]
END = "send this to the friend who's still healing from someone toxic"
