# (on-screen line, Tenor search used to find the clip)
LINES = [
 ("Your skinny girl era doesn't end at dinner", "cher clueless"),
 ("It ends at 9pm", "cinderella clock midnight"),
 ("in front of an open fridge", "opening fridge"),
 ("You're not hungry", "side eye"),
 ("You're bored", "spongebob bored"),
 ("Lonely", "bridget jones all by myself"),
 ("Putting something off", "lying on couch"),
 ("It's standing in the pantry", "shaggy scooby raid kitchen"),
 ("waiting for a snack to fix a feeling", "elle woods chocolate"),
 ("But chips can't fix boredom", "cookie monster eating"),
 ("They just fill the time", "waiting skeleton"),
 ("So you ask yourself", "roll safe thinking"),
 ("Would I eat an apple right now?", "snow white apple"),
 ("No? Then you're not hungry", "mic drop"),
 ("It's brushing your teeth at 8pm", "brushing teeth"),
 ("It's closing the kitchen like a restaurant", "we're closed"),
 ("It's tea instead of a treat", "kermit sipping tea"),
 ("Hands busy, mouth closed", "painting nails"),
 ("It's going to bed light", "sleeping beauty"),
 ("and waking up lighter", "waking up happy"),
 ("It's not “I can't snack”", "crying eating"),
 ("It's “I'm just not bored enough to eat”", "hair flip"),
 ("Sleep over snacks", "garfield sleeping"),
 ("Peace over impulse", "yoga zen"),
 ("Morning over midnight", "rapunzel morning"),
 ("Because in your skinny girl era", "marilyn monroe"),
 ("Boredom doesn't get a vote", "judge gavel"),
 ("And it definitely doesn't get a snack", "regina george"),
]
END = "share with someone\nwho SNACKS\nwhen they're\nBORED\nnot hungry"
