// 21 TikTok posts: 7 days x 3 per day. Snarky, provocative hooks → reveal ONE real hack from the Vault → "want the rest? link in bio".
// Roast habits and excuses, never bodies.
//
// Media: "key@sec" = a still frame from social/broll/<key>.mp4 at <sec> seconds (real stock footage from Mixkit).
// Carousel slide types:
//   meme   {img, text, sub?}                 caption text on top, photo below (hook slides)
//   photo  {img, kicker?, title, text, small?} photo on top, text card below (reveal / statement slides)
//   type   {img, name, text}                 quiz type slide
//   notes / imsg / search / tweet / check / sticky   "screenshot on purpose" slides
//   cta    {img}                             ebook + link in bio, over a photo
// Video types:
//   broll  {scenes:[{clip, at, d, text}]}    real clip playing under a caption (meme layout)
//   notes / imsg / search                   screen-recording style

const TAGS = "#theskinnylaws #skinnytips #weightlosstips #leanlifestyle #healthyhabits";

export const POSTS = [
// ───────────────────────── DAY 1 ─────────────────────────
{
  id: "d1-1-carousel-wish-i-knew", day: 1, time: "7:30 AM", format: "carousel",
  title: "I wish someone told me this sooner",
  slides: [
    { t: "meme", img: "crying@4", text: "I wish someone told me this before I wasted 3 years \"being good\" all day 😭", sub: "and then eating the entire kitchen at 9pm" },
    { t: "notes", title: "my \"healthy\" day 🙃", date: "Monday 7:02 AM", lines: ["☕ coffee for breakfast (\"not hungry\")", "🥗 sad little salad for lunch", "😇 \"so good\" all afternoon", "🍫 9pm: blackout snack mode", "", "i thought i had no willpower.", "i just had no breakfast."] },
    { t: "photo", img: "breakfast_eggs@4", kicker: "Here's the tea", title: "Night cravings are made in the morning.", text: "Eat like a bird all day and your body sends the bill at 9pm. With interest." },
    { t: "photo", img: "breakfast_done@2", kicker: "The hack: The Protein Anchor", title: "25–30g of protein within 2 hours of waking.", text: "Eggs + Greek yogurt. Cottage cheese toast. Protein latte + fruit. That's it.", small: "Hack #001 of 120 in the Vault 🔐" },
    { t: "check", title: "Steal these breakfasts", items: [["3 eggs + berries", true], ["Greek yogurt + granola + chia", true], ["Cottage cheese on toast + everything seasoning", true], ["Protein oats (scoop stirred in after cooking)", true]] },
    { t: "cta", img: "phone_type_v@3" },
  ],
  caption: "Not me thinking I had zero willpower when I literally just had zero breakfast 😭 The Protein Anchor fixed my nights in a week. It's hack #001 of 120 in The Skinny Laws Vault 🔐 link in bio",
  hashtags: TAGS + " #nightsnacking #proteinbreakfast #iwishiknew #relatable",
  pin: "The other 119 are in the Vault 🔐 link in bio",
},
{
  id: "d1-2-video-barely-eat", day: 1, time: "12:15 PM", format: "video",
  title: "POV: you 'barely eat'",
  video: { t: "broll", scenes: [
    { clip: "coffee_dance", at: 3, d: 3.0, text: "POV: you \"barely eat anything\" 🙄" },
    { clip: "donut_shake", at: 1, d: 3.2, text: "but your iced caramel latte has more sugar than this donut 🍩" },
    { clip: "salad_girl", at: 2, d: 3.2, text: "your \"light salad\" came with 4 tablespoons of creamy dressing 🥗" },
    { clip: "pizza", at: 1, d: 3.0, text: "and \"just one bite\" of everyone's food counts, bestie 🍕" },
    { clip: "popcorn_confused", at: 4, d: 3.4, text: "you're not broken. your drinks just don't fill you up." },
    { clip: "coffee_cafe", at: 2, d: 3.6, text: "fix: keep the coffee. ask for 1 pump + milk. that's hack #071 🔐" },
  ] },
  caption: "The math ain't mathing when your \"healthy\" coffee is basically dessert ☕😭 No shame, I was this girl. The Drink Laws in the Vault fixed it without me giving up my latte. Link in bio 🔐",
  hashtags: TAGS + " #themathaintmathing #coffeeorder #pov #relatable",
  pin: "Which one called you out? 😂",
},
{
  id: "d1-3-carousel-search-eat-less", day: 1, time: "8:00 PM", format: "carousel",
  title: "How do skinny people eat less?",
  slides: [
    { t: "meme", img: "eating_healthy_v@2", text: "Skinny girls don't have more willpower than you. They just know THIS 👀", sub: "swipe, it's almost annoying" },
    { t: "search", query: "how do skinny people eat less without trying", answer: "They don't rely on willpower. They eat in an order that makes them full faster: vegetables and protein first, carbs last.", source: "theskinnylaws.vault" },
    { t: "photo", img: "salad_girl@5", kicker: "The hack: Veggies Go First", title: "Same plate. Different order.", text: "Veg first, then protein, then carbs. You still eat everything — the carbs just go last.", small: "Studies on meal order show it can soften the blood sugar spike after eating. Fewer crashes = fewer cravings." },
    { t: "sticky", notes: ["1. veggies 🥦", "2. protein 🍗", "3. carbs 🍚", "that's literally it."] },
    { t: "cta", img: "wine_friend_v@4" },
  ],
  caption: "Same food. Different order. Zero willpower required 🤯 Hack #002 of 120 in The Skinny Laws Vault. Try it at dinner tonight → link in bio 🔐",
  hashtags: TAGS + " #foodorder #bloodsugar #eatingtips #skinnyhabits",
  pin: "Try it tonight and report back 👀",
},
// ───────────────────────── DAY 2 ─────────────────────────
{
  id: "d2-1-video-second-dinner", day: 2, time: "7:30 AM", format: "video",
  title: "Second dinner at 10:30pm",
  video: { t: "broll", scenes: [
    { clip: "tv_laugh", at: 3, d: 3.0, text: "dinner at 7. \"second dinner\" at 10:30. midnight toast. every night 🙃" },
    { clip: "popcorn_confused", at: 8, d: 3.0, text: "and then \"I don't know why I can't lose weight\"" },
    { clip: "wash_fruit", at: 3, d: 3.2, text: "what lean girls do instead: they CLOSE the kitchen. like a shop." },
    { clip: "tea_pour", at: 2, d: 3.2, text: "counter wiped. lights off. teeth brushed. tea made." },
    { clip: "sunset_walk", at: 1, d: 3.4, text: "minty mouth + closed kitchen = your brain stops asking for food ✨" },
    { clip: "laugh_yellow", at: 2, d: 3.0, text: "sounds dumb. works. hack #014 in the Vault 🔐" },
  ] },
  caption: "Your kitchen doesn't need to be open 24/7 babe 🌙 The Kitchen Closed Ritual is my favorite of the 120 hacks in The Skinny Laws Vault. Link in bio 🔐",
  hashtags: TAGS + " #nightsnacking #nightroutine #kitchenclosed #thatgirl",
  pin: "Be honest: what time does YOUR kitchen close? 😂",
},
{
  id: "d2-2-carousel-math-aint-mathing", day: 2, time: "12:15 PM", format: "carousel",
  title: "The math ain't mathing",
  slides: [
    { t: "meme", img: "popcorn_confused@6", text: "The math ain't mathing when you \"don't even eat that much\" but…", sub: "a loving roast 🔥 (I was ALL of these)" },
    { t: "tweet", text: "\"I never snack\" — the handful of chips every time you walk past the kitchen: 👋" },
    { t: "tweet", text: "\"I eat so clean\" — 3 tablespoons of peanut butter \"on\" a rice cake 🥜" },
    { t: "tweet", text: "\"I was good all week\" — the weekend: brunch, 4 margaritas, and a 2am drive-thru 🌮" },
    { t: "photo", img: "donut_shake@3", kicker: "No shame, just facts", title: "It's not your metabolism. It's the stuff you don't count.", text: "Bites, licks, drinks and weekends. They add up fast and fill you up never." },
    { t: "photo", img: "tv_laugh@5", kicker: "The hack: Bowl It, Never Bag It", title: "A bag has no bottom. A bowl does.", text: "Snack? Put a portion in a bowl, put the bag away, THEN sit down.", small: "Hack #012 of 120 🔐" },
    { t: "cta", img: "phone_type_v@5" },
  ],
  caption: "Not me finding out my \"small snacks\" were a whole extra meal 😭 Which one called you out? The Vault has 120 hacks to fix this without dieting. Link in bio 🔐",
  hashtags: TAGS + " #themathaintmathing #snacking #roast #relatable",
  pin: "Comment the number that exposed you 1, 2 or 3 😂",
},
{
  id: "d2-3-video-notes-lean-habits", day: 2, time: "8:00 PM", format: "video",
  title: "Notes: lean girl habits",
  video: { t: "notes", title: "habits of girls who stay lean without trying 🤫", date: "Tuesday 8:14 PM", lines: [
    "1. walk 10 min after dinner (not the gym)",
    "2. plate food in the kitchen, never family-style",
    "3. order FIRST at restaurants",
    "4. protein at breakfast. every. day.",
    "5. phone sleeps outside the bedroom",
    "6. never eat from the bag",
    "",
    "none of this is a diet.",
    "that's why it works. and why you've never heard it.",
  ] },
  onScreenHook: "they'll never tell you this so I will 📝",
  caption: "None of these feel like dieting and that's exactly why they work 📝 Each one is explained step-by-step (plus 114 more) in The Skinny Laws Vault. Link in bio 🔐",
  hashtags: TAGS + " #notesapp #thatgirlhabits #leangirl #healthyroutine",
  pin: "Number 3 is the one nobody believes 👀",
},
// ───────────────────────── DAY 3 ─────────────────────────
{
  id: "d3-1-carousel-start-monday", day: 3, time: "7:30 AM", format: "carousel",
  title: "'I'll start again Monday'",
  slides: [
    { t: "meme", img: "head_hands@3", text: "\"I'll start again Monday\" has started 52 Mondays a year, babe.", sub: "here's why you keep ending up back here 👇" },
    { t: "photo", img: "cushion_worried@4", kicker: "The loop", title: "Perfect → one slip → \"ruined\" → eat everything → Monday.", text: "Scientists literally have a name for it: the what-the-hell effect." },
    { t: "sticky", notes: ["one cookie ≠ ruined day", "next meal = normal meal", "no skipping to \"make up\"", "never miss twice."] },
    { t: "photo", img: "sunset_walk@3", kicker: "The hack: Never Miss Twice", title: "Slip once? Fine. Just make the next meal normal.", text: "Not skipped. Not a punishment. Not a Monday restart. Normal.", small: "From The Mindset Laws in the Vault 🔐" },
    { t: "cta", img: "phone_type_v@2" },
  ],
  caption: "You don't need a fresh start on Monday. You need a normal next meal 🧠 This rule ended my all-or-nothing era. The Mindset Laws are in the Vault → link in bio 🔐",
  hashtags: TAGS + " #allornothing #startmonday #mindset #nevermisstwice",
  pin: "Save this for your next \"I ruined it\" day 📌",
},
{
  id: "d3-2-video-search-sleep-hungry", day: 3, time: "12:15 PM", format: "video",
  title: "Search: hungry after bad sleep",
  video: { t: "search", query: "why am i so hungry the day after bad sleep", answer: "Short sleep raises ghrelin (your hunger hormone) and lowers leptin (your fullness hormone). Sleep-deprived people often snack more the next day.", after: ["so it wasn't a willpower problem…", "it was a 1am TikTok problem 😭"] },
  onScreenHook: "I finally googled it and I'm offended",
  caption: "The day after bad sleep I'm a bottomless pit and now I know why 😭 The Sleep & Stress Laws in the Vault have the fix (no, it's not \"just sleep more\"). Link in bio 🔐",
  hashtags: TAGS + " #sleep #ghrelin #alwayshungry #didyouknow",
  pin: "The Caffeine Curfew hack changed my sleep in a week 👀",
},
{
  id: "d3-3-carousel-smoothie", day: 3, time: "8:00 PM", format: "carousel",
  title: "You're not gonna like this: smoothies",
  slides: [
    { t: "meme", img: "smoothie_make@12", text: "You're not gonna like this, but… your \"healthy\" smoothie is why you're starving by 10am", sub: "🥤👀" },
    { t: "photo", img: "wash_fruit@5", kicker: "Here's the thing", title: "Drinking fruit ≠ eating fruit.", text: "3 bananas go down in 90 seconds. Your stomach barely notices drinks." },
    { t: "imsg", msgs: [{ me: false, text: "but smoothies are healthy??" }, { me: true, text: "they can be! but a fruit-only one is basically juice with a gym membership" }, { me: false, text: "rude. accurate. so what do i do" }, { me: true, text: "add protein, less fruit, and CHEW something with it" }] },
    { t: "photo", img: "eating_healthy_v@4", kicker: "The hack: Chew Your Fruit", title: "Protein in. Fruit down to 1 cup. Chew something.", text: "Add Greek yogurt or a scoop of protein, and eat something crunchy on the side.", small: "From The Drink Laws in the Vault 🔐" },
    { t: "cta", img: "wine_friend_v@6" },
  ],
  caption: "I'm not saying quit your smoothie. I'm saying fix it 🥤 This is one of 120 hacks in The Skinny Laws Vault. Link in bio 🔐",
  hashtags: TAGS + " #smoothie #notgonnalikethis #proteinsmoothie #hungry",
  pin: "Did you know this?? 😳",
},
// ───────────────────────── DAY 4 ─────────────────────────
{
  id: "d4-1-video-slow-metabolism", day: 4, time: "7:30 AM", format: "video",
  title: "I thought I had a slow metabolism",
  video: { t: "broll", scenes: [
    { clip: "insomnia", at: 5, d: 3.0, text: "I thought I had a slow metabolism 🙃" },
    { clip: "tv_laugh", at: 8, d: 3.0, text: "turns out I was just… sitting. all. day." },
    { clip: "headphones_walk", at: 2, d: 3.8, text: "the calories you burn NOT working out (walking, cleaning, standing) can beat a gym session" },
    { clip: "dance_music", at: 4, d: 3.0, text: "it's called NEAT. nobody talks about it." },
    { clip: "sunset_walk", at: 1, d: 3.4, text: "now: 10 min walk after every meal + every phone call is a walking call" },
    { clip: "plants_dance", at: 3, d: 3.2, text: "zero extra gym. different body. hack #031 🔐" },
  ] },
  caption: "It wasn't my metabolism. It was my chair 🪑😭 The Movement Laws (lazy-girl version) are in the Vault. Link in bio 🔐",
  hashtags: TAGS + " #slowmetabolism #neat #walking #lazygirlworkout",
  pin: "The 10-Minute Digestion Walk is hack #032 🔐",
},
{
  id: "d4-2-carousel-bestie-order-first", day: 4, time: "12:15 PM", format: "carousel",
  title: "Bestie asked how I eat out & stay lean",
  slides: [
    { t: "meme", img: "friends_night@4", text: "My bestie asked how I go out every weekend and still look like this", sub: "so I told her the truth 👇" },
    { t: "imsg", msgs: [{ me: false, text: "ok how do u eat out 3x a week and still look like that" }, { me: true, text: "i order first" }, { me: false, text: "…what" }, { me: true, text: "people copy the table. if you order last you end up with the burger everyone got" }, { me: false, text: "that can't be it" }] },
    { t: "imsg", msgs: [{ me: true, text: "i also stalk the menu online before we go" }, { me: true, text: "and i pick ONE treat. drinks OR bread OR dessert. not all 3" }, { me: false, text: "ok that's actually genius" }, { me: true, text: "i know 💅" }] },
    { t: "photo", img: "coffee_friends@3", kicker: "The hack: Order First + Pick One", title: "Read the menu before. Order first. One treat.", text: "You still go out. You still have fun. You just stop eating on autopilot.", small: "The Eating-Out & Social Laws — Vault 🔐" },
    { t: "cta", img: "wine_friend_v@2" },
  ],
  caption: "I still go out every weekend. I just have a game plan 💅 The full Eating-Out Laws + a restaurant cheat sheet for 8 kinds of places are in the Vault. Link in bio 🔐",
  hashtags: TAGS + " #eatingout #restauranthacks #bestie #girlsnight",
  pin: "Tag the friend who always orders last and copies you 😂",
},
{
  id: "d4-3-video-craving-wave", day: 4, time: "8:00 PM", format: "video",
  title: "Cravings are a wave",
  video: { t: "broll", scenes: [
    { clip: "popcorn_confused", at: 1, d: 3.0, text: "omg I just found out how cravings actually work 🤯" },
    { clip: "headache", at: 3, d: 3.0, text: "a craving is a wave. it builds… peaks… then fades." },
    { clip: "bed_phone", at: 2, d: 3.2, text: "usually in about 10 minutes." },
    { clip: "tea_pour", at: 5, d: 3.4, text: "so now I say \"ok. in 10 minutes.\" set a timer. make tea." },
    { clip: "laugh_yellow", at: 5, d: 3.4, text: "half the time I forget I even wanted it 💀" },
    { clip: "coffee_dance", at: 10, d: 3.0, text: "the 10-Minute Wave — hack #021 🔐" },
  ] },
  caption: "Not \"never eat it\" — just \"not this second\" 🕙 The Craving Laws are in the Vault. Link in bio 🔐",
  hashtags: TAGS + " #cravings #ijustfoundout #urgesurfing #sugarcravings",
  pin: "Try it tonight and report back 👇",
},
// ───────────────────────── DAY 5 ─────────────────────────
{
  id: "d5-1-carousel-naturally-thin", day: 5, time: "7:30 AM", format: "carousel",
  title: "Things 'naturally thin' girls do",
  slides: [
    { t: "meme", img: "mirror_ready@6", text: "\"She's just naturally thin\" — no babe, she does these 5 things and never told you", sub: "📌 save this" },
    { t: "photo", img: "breakfast_eggs@6", kicker: "1", title: "She eats protein at breakfast.", text: "Not a sad coffee. Actual food. So 9pm her isn't feral." },
    { t: "photo", img: "sunset_walk@4", kicker: "2", title: "She walks after dinner.", text: "10 minutes. No gym. Every day." },
    { t: "photo", img: "coffee_friends@5", kicker: "3", title: "She orders first.", text: "And picks ONE treat when she's out." },
    { t: "photo", img: "tea_pour@4", kicker: "4", title: "Her kitchen closes.", text: "Teeth brushed, tea made, done." },
    { t: "photo", img: "stretch_morning@3", kicker: "5", title: "She never misses twice.", text: "One messy day? Next meal is normal. No Monday restart." },
    { t: "cta", img: "phone_type_v@4" },
  ],
  caption: "She's not stricter than you. She just has systems 💅 All 5 (and 115 more) are in The Skinny Laws Vault. Link in bio 🔐",
  hashtags: TAGS + " #naturallythin #thatgirl #habits #leangirl",
  pin: "Which one are you skipping? 👀",
},
{
  id: "d5-2-video-imsg-bag", day: 5, time: "12:15 PM", format: "video",
  title: "Not me eating from the bag",
  video: { t: "imsg", name: "Bestie 💕", msgs: [
    { me: false, text: "not me opening the chips for \"a few\"" },
    { me: false, text: "and now the bag is empty 🙃" },
    { me: true, text: "you ate from the bag didn't you" },
    { me: false, text: "…maybe" },
    { me: true, text: "babe. put a portion in a bowl. put the bag AWAY. then sit down" },
    { me: false, text: "that's so simple it's annoying" },
    { me: true, text: "a bag has no bottom. a bowl does 🥣" },
  ] },
  onScreenHook: "not me… eating from the bag again 🙃",
  caption: "A bag has no bottom. A bowl does 🥣 One of the easiest Kitchen Laws in the Vault. Link in bio for the other 119 🔐",
  hashtags: TAGS + " #notme #snacking #portioncontrol #relatable",
  pin: "Be honest… bowl or bag? 😂",
},
{
  id: "d5-3-carousel-excuses", day: 5, time: "8:00 PM", format: "carousel",
  title: "Your excuses aren't excusing",
  slides: [
    { t: "meme", img: "laugh_yellow@3", text: "Your excuses aren't excusing, bestie 💅", sub: "(said with love, I used all of these)" },
    { t: "tweet", text: "\"It's my genetics\" — nah, it's your DoorDash history 📱" },
    { t: "tweet", text: "\"I don't have time to eat healthy\" — you had time for 3 hours of TikTok tho 👀" },
    { t: "tweet", text: "\"I'm just a snacky person\" — that's not a personality, that's a pantry." },
    { t: "photo", img: "dance_music@6", kicker: "The hack: The Identity Sentence", title: "\"I'm someone who ___.\"", text: "e.g. \"I'm someone who walks after dinner.\" Write it. Prove it once today.", small: "Habits stick when they become who you are 🔐" },
    { t: "cta", img: "phone_type_v@6" },
  ],
  caption: "Stop trying harder. Build better systems 🧠 The Mindset Laws in the Vault changed how I think about all of this. Link in bio 🔐",
  hashtags: TAGS + " #excuses #roast #mindsetshift #selfimprovement",
  pin: "Comment your \"I'm someone who…\" sentence 👇",
},
// ───────────────────────── DAY 6 ─────────────────────────
{
  id: "d6-1-video-event-no-starving", day: 6, time: "7:30 AM", format: "video",
  title: "Day before an event (no starving)",
  video: { t: "broll", scenes: [
    { clip: "mirror_unhappy", at: 6, d: 3.0, text: "big event tomorrow? do NOT starve yourself." },
    { clip: "headache", at: 6, d: 3.0, text: "starving = cranky, puffy, and you'll inhale the buffet 💀" },
    { clip: "omelet", at: 3, d: 3.2, text: "eat normal meals: protein + cooked veggies." },
    { clip: "market_tomatoes", at: 4, d: 3.4, text: "skip salty takeout. add potassium: banana, potato, spinach." },
    { clip: "sunset_walk", at: 2, d: 3.0, text: "walk after dinner. no fizzy drinks or gum (hello, air bloat)." },
    { clip: "mirror_ready", at: 8, d: 3.2, text: "sleep early. walk in glowing ✨ hack #098 🔐" },
  ] },
  caption: "Crash dieting before an event backfires every single time. This is the calm version ✨ The De-Bloat Laws are in the Vault. Link in bio 🔐",
  hashtags: TAGS + " #debloat #eventprep #bloating #glowup",
  pin: "The 3-second posture trick for photos is in Law 10 too 👀",
},
{
  id: "d6-2-carousel-scale-3lbs", day: 6, time: "12:15 PM", format: "carousel",
  title: "Up 3 lbs overnight? Calm down.",
  slides: [
    { t: "meme", img: "mirror_unhappy@12", text: "Stepped on the scale, saw +3 lbs, and decided the whole week was ruined? 🙃", sub: "sit down. swipe." },
    { t: "search", query: "why did my weight go up 3 lbs overnight", answer: "Day-to-day weight changes are mostly water — from salt, carbs, hormones, stress and digestion. You can't gain 3 lbs of fat in a day.", source: "theskinnylaws.vault" },
    { t: "photo", img: "headache@8", kicker: "Meanwhile you:", title: "ate a whole pizza \"because what's the point\" 🍕", text: "The scale didn't ruin your week. The panic did." },
    { t: "photo", img: "stretch_morning@5", kicker: "The hack: The Weekly Average Rule", title: "Only trust the 7-day average.", text: "Weigh most mornings. Add them up. Divide. Compare week to week — never day to day.", small: "The Vault has a tracker that does the math for you 🔐" },
    { t: "cta", img: "phone_type_v@3" },
  ],
  caption: "The scale isn't lying, it's just talking about water 💧 Stop letting one number ruin your week. The Weekly Average Tracker is built into the Vault. Link in bio 🔐",
  hashtags: TAGS + " #scale #waterweight #weightfluctuations #maintenance",
  pin: "This saved my sanity 🙏",
},
{
  id: "d6-3-video-grocery-rules", day: 6, time: "8:00 PM", format: "video",
  title: "If it's in the house, you'll eat it at 11pm",
  video: { t: "broll", scenes: [
    { clip: "supermarket", at: 3, d: 3.0, text: "if it's in your house, you WILL eat it at 11pm. sorry." },
    { clip: "supermarket", at: 9, d: 3.0, text: "so my grocery rules: never shop hungry. ever." },
    { clip: "fruit_market", at: 6, d: 3.2, text: "the frozen aisle is my best friend: veg, berries, shrimp, edamame" },
    { clip: "market_tomatoes", at: 10, d: 3.2, text: "buy flavor, not calories: hot sauce, salsa, lemon, spices" },
    { clip: "popcorn_confused", at: 12, d: 3.0, text: "trigger snacks stay at the store. bye 👋" },
    { clip: "wash_fruit", at: 8, d: 3.2, text: "full Lean Grocery List is in the Vault 🔐" },
  ] },
  caption: "If it's not in the house, you can't eat it at 11pm 🤷‍♀️ The full tick-box Lean Grocery List is a bonus in the Vault. Link in bio 🔐",
  hashtags: TAGS + " #groceryhaul #grocerytips #mealprep #healthygrocery",
  pin: "What's your #1 grocery staple? 👇",
},
// ───────────────────────── DAY 7 ─────────────────────────
{
  id: "d7-1-carousel-eating-types", day: 7, time: "7:30 AM", format: "carousel",
  title: "Which eating type are you?",
  slides: [
    { t: "meme", img: "tv_laugh@10", text: "Which eating type are you? 👀 Be honest.", sub: "this explains SO much" },
    { t: "type", img: "popcorn_confused@10", name: "🍿 The Grazer", text: "No real meals. Just nibbles. All. Day. Never actually full." },
    { t: "type", img: "headache@4", name: "😮‍💨 The Stress Eater", text: "Bad text = snack cupboard. Food is your off-switch." },
    { t: "type", img: "bed_phone@6", name: "🌙 The Night Nibbler", text: "\"Good\" all day. Then 9pm arrives and it all falls apart." },
    { t: "type", img: "friends_night@7", name: "🥂 The Weekend Rebounder", text: "Perfect Mon–Fri. Brunch, drinks, takeout… restart Monday." },
    { t: "photo", img: "laugh_yellow@6", kicker: "Here's the thing", title: "Each type needs different hacks.", text: "That's why generic diet advice never worked for you. The Vault has a 60-second quiz that tells you exactly where to start." },
    { t: "cta", img: "phone_type_v@5" },
  ],
  caption: "Comment your type 👇 I'm a recovering Night Nibbler 🌙 Take the full quiz inside The Skinny Laws Vault. It tells you which hacks to start with. Link in bio 🔐",
  hashtags: TAGS + " #whichoneareyou #eatingtype #personalitytest #relatable",
  pin: "Grazer, Stress Eater, Night Nibbler or Weekend Rebounder? 👇",
},
{
  id: "d7-2-video-skinny-fat", day: 7, time: "12:15 PM", format: "video",
  title: "Smaller isn't the goal",
  video: { t: "broll", scenes: [
    { clip: "mirror_unhappy", at: 16, d: 3.0, text: "lost weight but still don't look \"toned\"? 🙃" },
    { clip: "cushion_worried", at: 6, d: 3.2, text: "eating like a bird + 2 hrs of cardio can cost you muscle, not just fat" },
    { clip: "dumbbell_squat", at: 3, d: 3.4, text: "what actually changed my shape: protein every meal + lifting 2x a week" },
    { clip: "dumbbell_lunge", at: 4, d: 3.0, text: "20 minutes. full body. that's enough to start." },
    { clip: "pilates_home", at: 2, d: 3.0, text: "\"but I'll get bulky\" — babe, that takes YEARS on purpose 💀" },
    { clip: "mirror_ready", at: 3, d: 3.2, text: "smaller isn't the goal. firm is. The Shape Laws 🔐" },
  ] },
  caption: "Stop shrinking yourself. Build something instead 💪 The Shape Laws in the Vault have a beginner plan: 2 short sessions a week. Link in bio 🔐",
  hashtags: TAGS + " #skinnyfat #strengthtraining #protein #toned",
  pin: "Law 11 = The Shape Laws 💪 link in bio",
},
{
  id: "d7-3-carousel-whats-inside", day: 7, time: "8:00 PM", format: "carousel",
  title: "What's inside the Vault",
  slides: [
    { t: "meme", img: "phone_type_v@1", text: "I put every hack that actually worked into ONE place. No starving. No detox tea. No BS.", sub: "here's what's inside 🔐" },
    { t: "toc" },
    { t: "check", title: "Also inside", items: [["60-second eating-type quiz", true], ["30-Day Skinny Laws Challenge", true], ["Lean Grocery List (tick-box)", true], ["Restaurant cheat sheet — 8 places", true], ["Weekly average tracker", true], ["A roast on every single hack 🔥", true]] },
    { t: "photo", img: "sunset_walk@5", kicker: "Works on your phone", title: "Tap any section. Jump straight there.", text: "Search all 120 hacks, tick off what you tried, save your favorites." },
    { t: "cta", img: "wine_friend_v@8" },
  ],
  caption: "12 Laws. 120 hacks. Quiz, 30-day challenge, grocery list, restaurant cheat sheet + tracker 🔐 Everything I wish I'd had when I started. Link in bio.",
  hashtags: TAGS + " #digitalproduct #ebook #weightlossguide #selfimprovement",
  pin: "Questions about the Vault? Ask me here 👇",
},
];
