// 21 TikTok posts: 7 days x 3 per day. Every post teases ONE hack from the Vault, then points to the link in bio.
// format: "carousel" (photo mode, swipe) or "video". Slides/scenes are rendered by render.mjs.

const CTA_LINE = "The Skinny Laws Vault — 120 hacks like this. Link in bio.";
const TAGS_BASE = "#theskinnylaws #skinnytips #weightlosstips #healthyhabits #leanlifestyle";

export const POSTS = [
// ───────────────────────── DAY 1 ─────────────────────────
{
  id: "d1-1-carousel-night-hunger", day: 1, time: "7:30 AM", format: "carousel",
  title: "Night hunger starts at breakfast",
  slides: [
    { t: "hook", text: "I stopped snacking at night after I found out this ONE thing", sub: "and I'm actually mad nobody told me sooner 😳", bg: "window" },
    { t: "notes", title: "things i was doing wrong 🙃", date: "Monday 7:02 AM", lines: ["☕ coffee for breakfast", "🥗 tiny \"healthy\" lunch", "😇 being \"so good\" all day", "🍫 then eating the whole kitchen at 9pm", "", "i thought i had no willpower.", "i just had no breakfast."] },
    { t: "big", kicker: "The law", text: "Night cravings are usually made in the morning.", small: "A light, low-protein day leaves you under-fed by evening. Your body is just catching up." },
    { t: "tip", num: "THE HACK", title: "The Protein Anchor", text: "Eat 25–30g of protein within a couple of hours of waking up. Eggs + Greek yogurt. Cottage cheese toast. A protein latte + fruit.", small: "Protein keeps you fuller for longer than carbs or fat, so the 9pm panic never shows up." },
    { t: "check", title: "Protein anchor ideas (steal these)", items: [["3 eggs + berries", true], ["Greek yogurt + granola + chia", true], ["Cottage cheese + everything-bagel seasoning on toast", true], ["Protein oats (stir in a scoop after cooking)", false]] },
    { t: "big", kicker: "Keep going", text: "That was 1 hack. There are 119 more.", small: "The one that fixed my weekends is in the Eating-Out Laws." },
    { t: "cta" },
  ],
  caption: "I really thought I just had zero willpower at night 😭 turns out I was just under-fed all day. The Protein Anchor changed my evenings in like a week. This is 1 of 120 hacks inside The Skinny Laws Vault 🔐 link in bio",
  hashtags: TAGS_BASE + " #nightsnacking #proteinbreakfast #highprotein #cravings",
  pin: "Want the other 119? The Vault is in my bio 🔐",
},
{
  id: "d1-2-video-imsg-past-me", day: 1, time: "12:15 PM", format: "video",
  title: "Text from past me",
  video: { t: "imsg", name: "Past Me 🙄", msgs: [
    { me: false, text: "why am i ALWAYS hungry?? i barely eat" },
    { me: true, text: "babe you had a latte and 6 almonds" },
    { me: false, text: "exactly. i'm being good" },
    { me: true, text: "you're being hungry. that's different" },
    { me: false, text: "so what do i do" },
    { me: true, text: "eat MORE food that fills you up. protein first, then veggies, then carbs" },
    { me: false, text: "that's it??" },
    { me: true, text: "that's it. i stopped thinking about food 24/7 within a week" },
    { me: true, text: "there's 119 more where that came from 🔐" },
  ] },
  onScreenHook: "texting my past self the ONE thing she needed to hear 📲",
  caption: "If I could send ONE text to past me… 📲 Stop \"being good\" and start eating food that actually fills you up. The full list of 120 hacks is in the Vault — link in bio 🔐",
  hashtags: TAGS_BASE + " #pov #alwayshungry #pastme #weightlossjourney",
  pin: "The eating order hack is Law 01 in the Vault 👆 link in bio",
},
{
  id: "d1-3-carousel-google-eat-less", day: 1, time: "8:00 PM", format: "carousel",
  title: "How do skinny people eat less?",
  slides: [
    { t: "hook", text: "I googled \"how do skinny people eat less\" and the answer changed everything", sub: "swipe →", bg: "blush" },
    { t: "google", query: "how do skinny people eat less without trying", answer: "They don't rely on willpower. They eat in an order that makes them full faster: vegetables and protein first, carbs last.", source: "theskinnylaws.vault" },
    { t: "big", kicker: "Wait, what?", text: "Same plate. Different order. You get full sooner.", small: "Studies on meal order show eating veg + protein before carbs can lower the blood sugar spike after the meal — and fewer crashes means fewer cravings later." },
    { t: "tip", num: "THE HACK", title: "The Veggie-First Rule", text: "Eat your veggies first, then your protein, then your carbs. Don't skip the carbs — just eat them last.", small: "It takes zero willpower. You're still eating everything on your plate." },
    { t: "sticky", notes: ["1. veggies 🥦", "2. protein 🍗", "3. carbs 🍚", "(that's the whole hack)"] },
    { t: "cta" },
  ],
  caption: "Same food. Different order. That's literally it 🤯 The Veggie-First Rule is one of 120 hacks in The Skinny Laws Vault. Link in bio before you eat dinner tonight 🔐",
  hashtags: TAGS_BASE + " #foodorder #bloodsugar #eatingtips #skinnyhabits",
  pin: "Try it at dinner tonight and tell me if you notice 👀",
},
// ───────────────────────── DAY 2 ─────────────────────────
{
  id: "d2-1-video-overlay-kitchen-closed", day: 2, time: "7:30 AM", format: "video",
  title: "The kitchen-closed ritual",
  video: { t: "overlay", scenes: [
    { text: "I used to snack every single night.", d: 2.6 },
    { text: "Then I stole one habit from naturally thin people…", d: 3 },
    { text: "They \"close\" the kitchen after dinner. Like a shop.", d: 3 },
    { text: "Lights off. Counter wiped. Teeth brushed. Tea made.", d: 3.2 },
    { text: "Minty mouth + a closed kitchen = your brain stops asking for food.", d: 3.4 },
    { text: "It sounds silly. It works.", d: 2.4 },
  ], broll: ["Wiping a kitchen counter (close-up)", "Switching off the kitchen light", "Brushing teeth in a mirror (face not needed)", "Pouring hot water into a mug of tea", "Walking away to the couch with the tea"] },
  onScreenHook: "the 2-minute night ritual that ended my snacking 🌙",
  caption: "The \"Kitchen Closed\" ritual 🌙 I do it every night and I genuinely forgot about late snacks. It's in The Kitchen Laws — Law 02 of 12 in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #nightroutine #thatgirl #kitchenclosed #nosnacking",
  pin: "Full night routine + 119 more hacks in the Vault (bio) 🔐",
},
{
  id: "d2-2-carousel-roast-math", day: 2, time: "12:15 PM", format: "carousel",
  title: "The math ain't mathing (drinks)",
  slides: [
    { t: "hook", text: "The math ain't mathing when you \"barely eat\" but…", sub: "a gentle roast 🔥 (I was this girl)", bg: "ink" },
    { t: "tweet", text: "\"I barely eat anything\" — girl, your iced caramel latte has more sugar than a donut 🍩" },
    { t: "tweet", text: "\"I only had a salad\" — with 4 tablespoons of creamy dressing and croutons 🥗" },
    { t: "tweet", text: "\"I don't even snack\" — the \"one bite\" of everyone's fries counts, bestie 🍟" },
    { t: "big", kicker: "No shame", text: "Liquid calories don't fill you up.", small: "Your body barely counts drinks as food. You still get hungry for your next meal like the drink never happened." },
    { t: "tip", num: "THE HACK", title: "The Coffee Order Audit", text: "Keep your coffee. Just ask for half the syrup (or 1 pump) and milk instead of cream. Same ritual, way less sugar.", small: "Most people never notice the taste change after 3 days." },
    { t: "cta" },
  ],
  caption: "Not me realizing my \"healthy\" coffee was basically dessert 😭☕ The Drink Laws in the Vault fixed this without me giving up my latte. Link in bio 🔐",
  hashtags: TAGS_BASE + " #themathaintmathing #coffeeorder #liquidcalories #relatable",
  pin: "Which one got you? 😂 (1, 2 or 3)",
},
{
  id: "d2-3-video-notes-habits", day: 2, time: "8:00 PM", format: "video",
  title: "Notes app: things lean girls do",
  video: { t: "notes", title: "lean girl habits nobody talks about 🤫", date: "Tuesday 8:14 PM", lines: [
    "1. 10 min walk after dinner (not the gym)",
    "2. plate food in the kitchen, never family-style",
    "3. order FIRST at restaurants",
    "4. protein at every meal",
    "5. phone out of the bedroom",
    "6. they never eat from the bag",
    "",
    "none of these feel like a diet.",
    "that's the whole point.",
  ] },
  onScreenHook: "my notes app says it all 📝",
  caption: "None of these feel like dieting and that's exactly why they work 📝 Each one is explained step-by-step (plus 114 more) in The Skinny Laws Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #notesapp #thatgirlhabits #leangirl #healthyroutine",
  pin: "Number 3 surprised everyone 👀 it's in the Eating-Out Laws",
},
// ───────────────────────── DAY 3 ─────────────────────────
{
  id: "d3-1-carousel-sticky-fridge", day: 3, time: "7:30 AM", format: "carousel",
  title: "5 notes on my fridge",
  slides: [
    { t: "hook", text: "I wrote 5 rules on my fridge and my whole relationship with food changed", sub: "save this 📌", bg: "window" },
    { t: "sticky", notes: ["Hungry or bored? Wait 10 min.", "Plate it. Never eat from the bag.", "Protein first.", "Kitchen closes after dinner."] },
    { t: "big", kicker: "Rule 5 was the big one", text: "\"Never miss twice.\"", small: "One off day doesn't ruin anything. Two in a row starts a new habit. So after a messy day, the next meal is just normal. No punishing, no restarting on Monday." },
    { t: "tip", num: "THE HACK", title: "Never Miss Twice", text: "After a big meal or a messy day, make the very next meal a normal one. Not a skipped one. Not a Monday restart.", small: "This kills the 'all-or-nothing' spiral that makes most people quit." },
    { t: "cta" },
  ],
  caption: "Rule 5 literally rewired my brain 🧠 no more \"I'll start again Monday.\" It's from The Mindset Laws in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #fridgenotes #mindset #nevermisstwice #allornothing",
  pin: "Save it for your next \"I ruined it\" day 📌",
},
{
  id: "d3-2-video-google-hungry", day: 3, time: "12:15 PM", format: "video",
  title: "Google: why am I always hungry",
  video: { t: "google", query: "why am i so hungry the day after bad sleep", answer: "Short sleep raises ghrelin (your hunger hormone) and lowers leptin (your fullness hormone). Sleep-deprived people often eat more the next day, mostly snacks.", after: ["so it wasn't a willpower problem…", "it was a sleep problem 😭"] },
  onScreenHook: "I finally googled it…",
  caption: "The day after bad sleep I'm a bottomless pit and now I know why 😭 The Sleep & Stress Laws have the fix (no, it's not \"just sleep more\"). Link in bio 🔐",
  hashtags: TAGS_BASE + " #sleep #ghrelin #alwayshungry #didyouknow",
  pin: "The 'tired or hungry?' check is my favourite hack in Law 05 👀",
},
{
  id: "d3-3-carousel-not-gonna-like-smoothie", day: 3, time: "8:00 PM", format: "carousel",
  title: "You're not gonna like this: smoothies",
  slides: [
    { t: "hook", text: "You're not gonna like this, but… your smoothie might be why you're always hungry", sub: "🥤👀", bg: "blush" },
    { t: "big", kicker: "Here's the thing", text: "Drinking fruit ≠ eating fruit.", small: "Blending makes it fast to drink, and drinks don't fill you up like chewing does. 3 bananas go down in 90 seconds." },
    { t: "imsg", msgs: [{ me: false, text: "but smoothies are healthy??" }, { me: true, text: "they can be! but a fruit-only one is basically juice with fiber" }, { me: false, text: "so i'm hungry by 10am 😩" }, { me: true, text: "add protein + chew something with it" }] },
    { t: "tip", num: "THE HACK", title: "Chew Your Fruit", text: "Keep the smoothie if you love it, but add a scoop of protein or Greek yogurt, cut the fruit to 1 cup, and eat something crunchy with it.", small: "Or just eat the fruit whole. Your jaw is part of your fullness system." },
    { t: "cta" },
  ],
  caption: "I'm not saying quit your smoothie. I'm saying fix it 🥤 This is from The Drink Laws — one of 12 Laws in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #smoothie #notgonnalikethis #proteinsmoothie #hungry",
  pin: "Did you know this?? 😳",
},
// ───────────────────────── DAY 4 ─────────────────────────
{
  id: "d4-1-video-overlay-slow-metabolism", day: 4, time: "7:30 AM", format: "video",
  title: "I thought I had a slow metabolism",
  video: { t: "overlay", scenes: [
    { text: "I thought I had a slow metabolism.", d: 2.6 },
    { text: "Turns out I was just… sitting. All day.", d: 2.8 },
    { text: "The calories you burn NOT working out (walking, standing, cleaning) can be bigger than a gym session.", d: 4 },
    { text: "It's called NEAT.", d: 2.2 },
    { text: "Now I walk 10 min after every meal. Phone calls = walking calls.", d: 3.4 },
    { text: "Zero gym. Different body.", d: 2.4 },
  ], broll: ["Feet walking on a sidewalk (golden hour)", "Pressing 'play' on a podcast while putting on sneakers", "Walking while on a phone call (no face needed)", "Taking the stairs", "Coffee cup on a window sill"] },
  onScreenHook: "I thought I had a slow metabolism… 🙃",
  caption: "It wasn't my metabolism. It was my chair 🪑😭 The Movement Laws (the lazy-girl version) are all about this. 1 of 12 Laws in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #slowmetabolism #neat #walking #lazygirlworkout",
  pin: "The 10-minute walk after meals is Law 04 🔐",
},
{
  id: "d4-2-carousel-imsg-restaurant", day: 4, time: "12:15 PM", format: "carousel",
  title: "Bestie, order first",
  slides: [
    { t: "hook", text: "my bestie asked how I stay lean when we go out every weekend", sub: "so I told her the truth 👇", bg: "window" },
    { t: "imsg", msgs: [{ me: false, text: "ok how do u eat out 3x a week and still look like that" }, { me: true, text: "i order first" }, { me: false, text: "…what" }, { me: true, text: "people copy the table. if you order first, you pick what you actually want" }, { me: false, text: "that can't be it" }] },
    { t: "imsg", msgs: [{ me: true, text: "i also read the menu online before we go" }, { me: true, text: "and i decide my ONE treat. drinks OR dessert OR bread. not all 3" }, { me: false, text: "ok that's actually genius" }, { me: true, text: "i know 💅" }] },
    { t: "tip", num: "THE HACK", title: "Order First + Pick One", text: "Read the menu before you go. Order first. Pick ONE treat (drink, bread or dessert) and enjoy it fully.", small: "You still go out. You still have fun. You just stop eating on autopilot." },
    { t: "cta" },
  ],
  caption: "I still go out every weekend. I just have a game plan 💅 The full Eating-Out & Social Laws (with a restaurant cheat sheet for 8 types of places) are in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #eatingout #restauranthacks #bestie #weekendvibes",
  pin: "Tag the friend who orders last and copies you 😂",
},
{
  id: "d4-3-video-notes-craving-10min", day: 4, time: "8:00 PM", format: "video",
  title: "Notes: cravings last ~10 minutes",
  video: { t: "notes", title: "i just found out 🤯", date: "Thursday 9:41 PM", lines: [
    "a craving is a wave.",
    "it builds… peaks… then fades.",
    "",
    "so now when i want the snack i say:",
    "\"ok. in 10 minutes.\"",
    "",
    "i set a timer. drink tea. text someone.",
    "",
    "half the time?? i forget i wanted it.",
    "the other half i eat it slowly and i'm fine.",
  ] },
  onScreenHook: "omg I just found out how cravings actually work",
  caption: "The 10-minute rule 🕙 Not \"never eat it\" — just \"not this second.\" It's in The Craving Laws inside the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #cravings #ijustfoundout #urgesurfing #mindfuleating",
  pin: "Try it tonight and report back 👇",
},
// ───────────────────────── DAY 5 ─────────────────────────
{
  id: "d5-1-carousel-checklist-night", day: 5, time: "7:30 AM", format: "carousel",
  title: "My kitchen-closed checklist",
  slides: [
    { t: "hook", text: "The nightly checklist that made me stop thinking about food after 8pm", sub: "screenshot it 📸", bg: "blush" },
    { t: "check", title: "Kitchen closed ✅", items: [["Dinner with protein + veggies", true], ["10 min walk", true], ["Wipe the counter & lights off", true], ["Brush teeth (mint = done eating)", true], ["Herbal tea on the couch", true], ["Phone charging OUTSIDE the bedroom", false]] },
    { t: "big", kicker: "Why the last one?", text: "Late scrolling = late snacking.", small: "Less sleep makes you hungrier tomorrow. Charging your phone in another room protects your sleep AND your cravings." },
    { t: "cta" },
  ],
  caption: "6 tiny things. Every night. That's it 🌙 Part of my 30-Day Skinny Laws Challenge inside the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #nightroutine #checklist #thatgirl #sleephygiene",
  pin: "Which one are you skipping? 👀",
},
{
  id: "d5-2-video-imsg-bag", day: 5, time: "12:15 PM", format: "video",
  title: "Not me eating from the bag",
  video: { t: "imsg", name: "Bestie 💕", msgs: [
    { me: false, text: "not me opening the chips for \"a few\"" },
    { me: false, text: "and now the bag is empty 🙃" },
    { me: true, text: "you ate from the bag didn't you" },
    { me: false, text: "…maybe" },
    { me: true, text: "never eat from the package. put a portion in a bowl. put the bag away. THEN sit down" },
    { me: false, text: "that's so simple it's annoying" },
    { me: true, text: "a bag has no bottom. a bowl does 🥣" },
  ] },
  onScreenHook: "not me… eating from the bag again 🙃",
  caption: "A bag has no bottom. A bowl does 🥣 One of the easiest Kitchen Laws in the Vault. Link in bio for the other 119 🔐",
  hashtags: TAGS_BASE + " #notme #snacking #portioncontrol #relatable",
  pin: "Be honest… bowl or bag? 😂",
},
{
  id: "d5-3-carousel-tweet-naturally-thin", day: 5, time: "8:00 PM", format: "carousel",
  title: "Nobody is naturally skinny",
  slides: [
    { t: "hook", text: "I'm just gonna leave this here…", sub: "📌", bg: "ink" },
    { t: "tweet", text: "the \"naturally thin\" girl isn't running on luck. she's running on systems she doesn't even notice anymore." },
    { t: "tweet", text: "she doesn't \"start Monday.\" she just never misses twice." },
    { t: "tweet", text: "she's not stricter than you. her environment just makes the easy choice the lean choice." },
    { t: "tip", num: "THE HACK", title: "The Identity Sentence", text: "Write one line: \"I'm someone who ___.\" (e.g. \"I'm someone who walks after dinner.\") Then prove it once today.", small: "Habits stick when they become who you are, not a rule you follow." },
    { t: "cta" },
  ],
  caption: "Stop trying harder. Build better systems 🧠 The Mindset Laws in the Vault changed the way I think about all of this. Link in bio 🔐",
  hashtags: TAGS_BASE + " #mindsetshift #identity #habits #naturallythin",
  pin: "Comment your \"I'm someone who…\" sentence 👇",
},
// ───────────────────────── DAY 6 ─────────────────────────
{
  id: "d6-1-video-overlay-event-debloat", day: 6, time: "7:30 AM", format: "video",
  title: "Day before an event (no starving)",
  video: { t: "overlay", scenes: [
    { text: "Big event tomorrow? Don't starve yourself.", d: 2.8 },
    { text: "Starving = cranky, dizzy + you'll overeat at the event.", d: 3 },
    { text: "Instead: eat normal meals. Protein + cooked veggies.", d: 3 },
    { text: "Go easy on salty takeout. Add potassium: banana, potato, spinach.", d: 3.4 },
    { text: "Skip the fizzy drinks + gum (hello, air bloat).", d: 3 },
    { text: "Walk after dinner. Sleep early. Glow tomorrow ✨", d: 3 },
  ], broll: ["Laying out an outfit on the bed", "Peeling a banana", "Plate of salmon + roasted veggies", "Evening walk (feet / sunset)", "Setting a phone alarm and switching off the lamp"] },
  onScreenHook: "what I do the day before an event (instead of starving) ✨",
  caption: "Crash dieting before an event backfires every time. This is the calm version ✨ The full De-Bloat Laws are in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #debloat #eventprep #bloating #glowup",
  pin: "Posture trick for photos is in Law 10 too 👀",
},
{
  id: "d6-2-carousel-google-scale", day: 6, time: "12:15 PM", format: "carousel",
  title: "Why the scale jumps",
  slides: [
    { t: "hook", text: "Why did I \"gain\" 3 lbs overnight?", sub: "(you didn't, relax) swipe →", bg: "window" },
    { t: "google", query: "why did my weight go up 3 lbs overnight", answer: "Day-to-day weight changes are mostly water — from salt, carbs, hormones, stress and digestion. You can't gain 3 lbs of fat in a day.", source: "theskinnylaws.vault" },
    { t: "big", kicker: "The fix", text: "Only trust the weekly average.", small: "Weigh most mornings. Add them up. Divide by the days. Compare week to week — not day to day." },
    { t: "tip", num: "THE HACK", title: "The Weekly Average Rule", text: "Weigh in the morning, same conditions. Ignore any single day. Watch the 7-day average go down slowly.", small: "The Vault has a built-in tracker that does this math for you." },
    { t: "cta" },
  ],
  caption: "The scale isn't lying, it's just talking about water 💧 Stop panicking at one number. The Weekly Average Tracker is built into the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #scale #waterweight #weightfluctuations #maintenance",
  pin: "This saved my sanity 🙏",
},
{
  id: "d6-3-video-notes-frozen-aisle", day: 6, time: "8:00 PM", format: "video",
  title: "Notes: my lean grocery secrets",
  video: { t: "notes", title: "grocery rules that keep me lean 🛒", date: "Saturday 10:03 AM", lines: [
    "✦ never shop hungry (eat first!)",
    "✦ the frozen aisle is my best friend",
    "   frozen veg, berries, shrimp, edamame",
    "✦ rotisserie chicken = 3 meals",
    "✦ buy flavor, not calories:",
    "   hot sauce, salsa, lemon, everything seasoning",
    "✦ trigger snacks stay at the store",
    "",
    "if it's not in the house, i can't eat it at 11pm 🤷‍♀️",
  ] },
  onScreenHook: "my grocery rules (steal them) 🛒",
  caption: "If it's not in the house, you can't eat it at 11pm 🤷‍♀️ The full Lean Grocery List (tick-box version) is a bonus in the Vault. Link in bio 🔐",
  hashtags: TAGS_BASE + " #groceryhaul #grocerytips #mealprep #frozenfood",
  pin: "What's your #1 grocery staple? 👇",
},
// ───────────────────────── DAY 7 ─────────────────────────
{
  id: "d7-1-carousel-quiz-type", day: 7, time: "7:30 AM", format: "carousel",
  title: "Which eating type are you?",
  slides: [
    { t: "hook", text: "Which eating type are you? 👀", sub: "this explains SO much", bg: "blush" },
    { t: "type", emoji: "🍿", name: "The Grazer", text: "No big meals. Just nibbles. All. Day. Never actually full." },
    { t: "type", emoji: "😮‍💨", name: "The Stress Eater", text: "Food is your off-switch. Bad text = snack cupboard." },
    { t: "type", emoji: "🌙", name: "The Night Nibbler", text: "\"Good\" all day. Then 9pm arrives and it all falls apart." },
    { t: "type", emoji: "🥂", name: "The Weekend Rebounder", text: "Perfect Mon–Fri. Brunch, drinks, takeout… restart Monday." },
    { t: "big", kicker: "Here's the thing", text: "Each type needs different hacks.", small: "That's why generic diet advice doesn't work for you. The Vault has a 60-second quiz that tells you exactly which Laws to start with." },
    { t: "cta" },
  ],
  caption: "Comment your type 👇 I'm a recovering Night Nibbler 🌙 Take the full quiz inside The Skinny Laws Vault and it tells you which hacks to start with. Link in bio 🔐",
  hashtags: TAGS_BASE + " #whichoneareyou #eatingtype #personalitytest #relatable",
  pin: "Grazer, Stress Eater, Night Nibbler or Weekend Rebounder? 👇",
},
{
  id: "d7-2-video-overlay-skinny-fat", day: 7, time: "12:15 PM", format: "video",
  title: "Stop only trying to lose weight",
  video: { t: "overlay", scenes: [
    { text: "Stop ONLY trying to lose weight.", d: 2.6 },
    { text: "If you just eat less, you can lose muscle too.", d: 2.8 },
    { text: "That's how you end up smaller… but softer. (\"skinny-fat\")", d: 3.2 },
    { text: "What changed my shape: protein at every meal + lifting 2x a week.", d: 3.6 },
    { text: "20 minutes. Full body. That's enough to start.", d: 2.8 },
    { text: "Lean ≠ just light. Lean = firm.", d: 2.6 },
  ], broll: ["Lacing up sneakers", "Picking up a pair of dumbbells at home", "Doing a slow squat (from the side, no face needed)", "Scooping protein powder into a shaker", "Mirror outfit check"] },
  onScreenHook: "stop ONLY trying to lose weight (do this instead)",
  caption: "Smaller isn't the goal. Firmer is 💪 The Shape Laws in the Vault have a beginner-friendly plan (2 short sessions a week). Link in bio 🔐",
  hashtags: TAGS_BASE + " #skinnyfat #strengthtraining #protein #toned",
  pin: "Law 11 = The Shape Laws 💪 link in bio",
},
{
  id: "d7-3-carousel-whats-inside", day: 7, time: "8:00 PM", format: "carousel",
  title: "What's inside the Vault",
  slides: [
    { t: "hook", text: "I put every hack that actually worked into ONE place", sub: "here's what's inside 🔐", bg: "ink" },
    { t: "toc" },
    { t: "check", title: "Also inside", items: [["60-second eating-type quiz", true], ["30-Day Skinny Laws Challenge", true], ["Lean Grocery List (tick-box)", true], ["Restaurant cheat sheet — 8 kinds of places", true], ["Weekly average tracker", true], ["Journal prompts for every Law", true]] },
    { t: "big", kicker: "No starving. No crash diets.", text: "Just 120 small hacks that make lean feel normal.", small: "Tap any section to jump straight there. Works on your phone." },
    { t: "cta" },
  ],
  caption: "12 Laws. 120 hacks. Quiz, 30-day challenge, grocery list, restaurant cheat sheet + tracker 🔐 Everything I wish I had when I started. Link in bio.",
  hashtags: TAGS_BASE + " #digitalproduct #ebook #weightlossguide #selfimprovement",
  pin: "Questions about the Vault? Ask me here 👇",
},
];

export const CTA = CTA_LINE;
